spring:
  application:
    name: payment-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: payment_db
      username: payment_user
      password: payment_pass
      authentication-database: admin

  kafka:
    bootstrap-servers: ${environment.kafka.address}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: payment-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'

server:
  port: 8082

payment:
  gateway:
    url: https://csrng.net/csrng/csrng.php

environment:
  kafka:
    address: localhost:9092